# Generated by Django 5.2 on 2025-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.FileField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
