# Generated by Django 5.2 on 2025-05-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='banner',
            new_name='Project_Document',
        ),
        migrations.AddField(
            model_name='post',
            name='Test_Case_File',
            field=models.FileField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='Test_Script_File',
            field=models.FileField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
