# Generated by Django 5.2 on 2025-05-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_banner_post_project_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Test_Case_File',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Test_Script_File',
        ),
    ]
