# Generated by Django 5.2 on 2025-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_project_document_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_document',
            field=models.FileField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
